name: 发版请求
description: 关闭后触发正式发布
title: 发版请求
labels: [release]
assignees: []

body:
  - type: markdown
    attributes:
      value: >
        本模板为固定流程，关闭 Issue 后将触发正式发布；如需修改发布类型，仅选择下列版本增量之一。
        </br>
        </br>
        ⚠️ 关键提示：请务必为本 Issue 追加 `release` 标签，否则 workflow 条件中会被跳过，不会触发发布。

  - type: dropdown
    id: bump_type
    attributes:
      label: 版本增量
      description: 选择本次发版版本提升方式
      options:
        - patch
        - minor
        - major
    validations:
      required: true
